[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @lucyn-tools/discord-bot build"

[deploy]
startCommand = "pnpm --filter @lucyn-tools/discord-bot start"
restartPolicyType = "always"
